// <auto-generated />
namespace MVCApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class contactAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201810040701507_contactAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
