CREATE TABLE BANK_MASTER(
	ACCOUNTNO INT PRIMARY KEY,
	NAME VARCHAR(20),
	BALANCE FLOAT,
	PASSWORD VARCHAR(20),
	DATECREATED DATETIME
);

SELECT * FROM LOGINUSERS

INSERT INTO BANK_MASTER(ACCOUNTNO,NAME,BALANCE,PASSWORD,DATECREATED)
VALUES(101,'CHANDAN',20000,'root',GETDATE())

INSERT INTO BANK_MASTER(ACCOUNTNO,NAME,BALANCE,PASSWORD,DATECREATED)
VALUES(102,'DHARMESH',20000,'superuser',GETDATE())

INSERT INTO BANK_MASTER(ACCOUNTNO,NAME,BALANCE,PASSWORD,DATECREATED)
VALUES(103,'FOO',20000,'foo',GETDATE())

SELECT * FROM BANK_MASTER

CREATE TABLE BANK_TRANSACTION(
	ACCOUNTNO INT REFERENCES BANK_MASTER(ACCOUNTNO),
	TRANSACTION_TYPE VARCHAR(20),
	AMOUNT FLOAT,
	TRANSACTION_DATE DATETIME 
)

SELECT * FROM BANK_TRANSACTION

SELECT * FROM dbo.BankTransactions
SELECT * FROM dbo.BankAccounts