USE Hitech
go

SELECT * FROM EMP WHERE DEPTNO=10 ORDER BY SAL DESC

SELECT * FROM EMP ORDER BY SAL DESC

SELECT * FROM EMP WHERE ENAME LIKE 'A%'

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE NOT DEPTNO=10

SELECT ENAME, ((SAL+ISNULL(COMM,0))*12) AS CTC FROM EMP

SELECT ENAME, DEPTNO FROM EMP

SELECT DISTINCT DEPTNO FROM EMP

SELECT HIREDATE, DATEDIFF(YEAR,HIREDATE,GETDATE()) AS TENURE FROM EMP

SELECT GETDATE() AS CURR_DATE

SELECT * FROM EMP WHERE JOB='MANAGER'

SELECT TOP 3 * FROM EMP ORDER BY SAL DESC

SELECT * FROM EMP WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT')

SELECT * FROM EMP WHERE JOB IN(SELECT JOB FROM EMP WHERE ENAME='SMITH')

SELECT * 
FROM EMP 
WHERE SAL 
IN(SELECT MAX(SAL)AS SECONDMAX 
	FROM EMP 
	WHERE SAL 
	NOT IN(SELECT MAX(SAL) 
			FROM EMP))
			
SELECT COUNT(*) AS HEADCOUNT,DEPTNO 
FROM EMP 
GROUP BY DEPTNO 
ORDER BY HEADCOUNT;

SELECT COUNT(*) AS HEADCOUNT,JOB 
FROM EMP 
GROUP BY JOB 
HAVING COUNT(*)>2 
ORDER BY HEADCOUNT;

SELECT * FROM EMP ORDER BY SAL;

SELECT DEPTNO,JOB,COUNT(JOB) AS HEADCOUNT 
FROM EMP
GROUP BY DEPTNO,JOB
ORDER BY DEPTNO;

CREATE TABLE COLLEGE(
	college_id INT IDENTITY PRIMARY KEY,
	college_name VARCHAR(20),
	college_location VARCHAR(20)
);

DROP TABLE COLLEGE

SELECT * FROM COLLEGE

INSERT INTO COLLEGE(college_name,college_location)
VALUES('GECD','Dahod');

INSERT INTO COLLEGE(college_name,college_location)
VALUES('SVNIT','Surat');

CREATE TABLE STUDENT2(
	student_id INT IDENTITY PRIMARY KEY,
	student_name VARCHAR(20),
	student_CGPA FLOAT(5),
	student_contact INT
);

ALTER TABLE STUDENT2
ADD student_college INT REFERENCES COLLEGE(college_id);

ALTER TABLE STUDENT2
ALTER COLUMN student_contact BIGINT;

SELECT * FROM STUDENT2;

INSERT INTO STUDENT2(student_name,student_CGPA,student_contact,student_college)
VALUES('Chandan',8.0,8460551251,1);

INSERT INTO STUDENT2(student_name,student_CGPA,student_contact,student_college)
VALUES('Dharmesh',9.0,8780421011,2);

INSERT INTO STUDENT2(student_name,student_CGPA,student_contact,student_college)
VALUES('Smith',8.6,1234567890,1);

--joins
SELECT e.ENAME ,d.DNAME
FROM EMP e JOIN DEPT d 
ON e.DEPTNO=d.DEPTNO;

SELECT d.DNAME,e.ENAME 
FROM DEPT d LEFT JOIN EMP e 
ON e.DEPTNO=d.DEPTNO;

SELECT d.DNAME,e.ENAME 
FROM DEPT d LEFT JOIN EMP e 
ON e.DEPTNO=d.DEPTNO
WHERE e.ENAME IS NULL;

SELECT d.DNAME,COUNT(e.ENAME)
FROM DEPT d LEFT JOIN EMP e 
ON e.DEPTNO=d.DEPTNO
GROUP BY d.DNAME;

SELECT x.ENAME AS EMPLOYEE,y.ENAME as MANAGER 
FROM EMP x LEFT JOIN EMP y 
ON x.MGR=y.EMPNO;

SELECT * 
FROM EMP;

SELECT * FROM STUDENT2

CREATE TABLE CONTACT(
	contact_id INT IDENTITY PRIMARY KEY,
	contact_number BIGINT,
	student_id INT REFERENCES STUDENT2(student_id)
);

INSERT INTO CONTACT(contact_number,student_id)
VALUES(8460551251,2);

SELECT * FROM CONTACT
